version: '3.8'

services:
  ravendb:
    image: ravendb/ravendb
    container_name: RavenDb-WithData
    ports:
      - "8080:8080"
      - "38888:38888"
    volumes:
      - /var/lib/ravendb/data
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
